#!/usr/bin/python
import unittest

import xhpy

class XHPyHookTests(unittest.TestCase):
  """
  Sanity checks. If the hook is working, these should all import successfully
  without exceptions.
  """
  def testNativeModules(self):
    import string
    import xml.dom.minidom
  def testCustomModules(self):
    import xhpy.tests.hook.simple_module

if __name__ == '__main__':
  unittest.main()
