#!/usr/bin/python

import xhpy.init

import array_constant; print '[array_constant] DONE'
import attr_blank; print '[attr_blank] DONE'
import attr_entity; print '[attr_entity] DONE'
import attr_float; print '[attr_float] DONE'
import attributes; print '[attributes] DONE'
import class_constants; print '[class_constants] DONE'
import docstrings_01; print '[docstrings_01] DONE'
import docstrings_02; print '[docstrings_02] DONE'
import docstrings_03; print '[docstrings_03] DONE'
import docstrings_05; print '[docstrings_05] DONE'
import klass; print '[klass] DONE'
# TODO: add support for inspect getsourcelines()
#import lineno_01; print '[lineno_01] DONE'
# TODO: add support for comment tokens within tags
#import lineno_02; print '[lineno_02] DONE'
import logical_op; print '[logical_op] DONE'
import stack_balance_fail; print '[stack_balance_fail] DONE'
import whitespace_01; print '[whitespace_01] DONE'
import whitespace_02; print '[whitespace_02] DONE'
import whitespace_03; print '[whitespace_03] DONE'
import whitespace_04; print '[whitespace_04] DONE'
import whitespace_05; print '[whitespace_05] DONE'
import whitespace_06; print '[whitespace_06] DONE'
import whitespace_07; print '[whitespace_07] DONE'
import xhpy_function_param; print '[xhpy_function_param] DONE'
