#!/usr/bin/python

from xhpy.init import register_xhpy_module

register_xhpy_module('array_constant'); import array_constant; print '[array_constant] DONE'
register_xhpy_module('attr_blank'); import attr_blank; print '[attr_blank] DONE'
register_xhpy_module('attr_entity'); import attr_entity; print '[attr_entity] DONE'
register_xhpy_module('attr_float'); import attr_float; print '[attr_float] DONE'
register_xhpy_module('attributes'); import attributes; print '[attributes] DONE'
register_xhpy_module('class_constants'); import class_constants; print '[class_constants] DONE'
register_xhpy_module('docstrings_01'); import docstrings_01; print '[docstrings_01] DONE'
register_xhpy_module('docstrings_02'); import docstrings_02; print '[docstrings_02] DONE'
register_xhpy_module('docstrings_03'); import docstrings_03; print '[docstrings_03] DONE'
register_xhpy_module('docstrings_05'); import docstrings_05; print '[docstrings_05] DONE'
register_xhpy_module('klass'); import klass; print '[klass] DONE'
# TODO: add support for inspect getsourcelines()
#register_xhpy_module('lineno_01'); import lineno_01; print '[lineno_01] DONE'
# TODO: add support for comment tokens within tags
#register_xhpy_module('lineno_02'); import lineno_02; print '[lineno_02] DONE'
register_xhpy_module('logical_op'); import logical_op; print '[logical_op] DONE'
register_xhpy_module('stack_balance_fail'); import stack_balance_fail; print '[stack_balance_fail] DONE'
register_xhpy_module('whitespace_01'); import whitespace_01; print '[whitespace_01] DONE'
register_xhpy_module('whitespace_02'); import whitespace_02; print '[whitespace_02] DONE'
register_xhpy_module('whitespace_03'); import whitespace_03; print '[whitespace_03] DONE'
register_xhpy_module('whitespace_04'); import whitespace_04; print '[whitespace_04] DONE'
register_xhpy_module('whitespace_05'); import whitespace_05; print '[whitespace_05] DONE'
register_xhpy_module('whitespace_06'); import whitespace_06; print '[whitespace_06] DONE'
register_xhpy_module('whitespace_07'); import whitespace_07; print '[whitespace_07] DONE'
register_xhpy_module('xhpy_function_param'); import xhpy_function_param; print '[xhpy_function_param] DONE'
