#!/bin/bash
#
# These are manual tests, essentially; all you want is to verify that it
# outputs something reasonable.
#
#
MYDIR=$(dirname $0)
for FILE in $MYDIR/*.py; do
  python $MYDIR/../../parser/XHPyParser.py < "$FILE"
done
